{% set version = "1.0.0" %}

package:
    name: wradlib
    version: {{ version }}

source:
    fn: wradlib-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/w/wradlib/wradlib-{{ version }}.tar.gz
    sha256: 156c66a639f9c2fca46c396a6c84ffa74ca6079359f0b40588de0e4a50f88ad0

build:
    number: 1
    script: python -m pip install --no-deps --ignore-installed .

requirements:
    build:
        - python
        - pip
        - deprecation
        - numpy
        - scipy
        - matplotlib
        - h5py
        - netcdf4
        - gdal 2.2.*
        - xmltodict
    run:
        - python
        - deprecation
        - numpy
        - scipy
        - matplotlib
        - h5py
        - netcdf4
        - gdal 2.2.*
        - xmltodict

test:
    imports:
        - wradlib  # [not osx]
    commands:
        # hack to get macosx matplotlib running
        # see https://github.com/conda-forge/wradlib-feedstock/pull/20
        - python -c "import matplotlib as mpl; mpl.use('Agg'); import wradlib"  # [osx]

about:
    home: http://wradlib.org/
    license: MIT
    summary: "Open Source Library for Weather Radar Data Processing"

extra:
    recipe-maintainers:
        - jjhelmus
        - kmuehlbauer
